### ISSUE TITLE
Document Integration with CI/CD pipelines

### ISSUE THREAD

**Issue by oxr463** [nicolasbock/ebuildtester#102]
e.g., via Travis, GitLab, Circle, etc.

**Comment by nicolasbock** [comment]
Hi!

Do you mean to document how this code is tested in CI?

**Comment by oxr463** [comment]
I meant, how to set it up on Travis or the like, to test an ebuild overlay.

**Comment by nicolasbock** [comment]
Ah. I think that's a little tricky because Travis imposes strict timeouts on the builds on their infrastructure. The limit on Travis is 50 minutes (https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts). I haven't found such a limit for circleci, but let's assume it's around an hour.

To test a package in CI you would have to build all dependencies that are not already included in the stage3. A package such as gnome or kde would require a large number of such packages and building them might take much longer than the CI timeout.

It would be interesting to see how far one could push this though. Do you want to take a stab at it? I can help you, but at this point I wouldn't have the spare cycles to do it myself.

**Comment by oxr463** [comment]
Here is my current configuration for GitLab CI/CD on my personal overlay:

- https://gitlab.com/oxr463/overlay/blob/master/.gitlab-ci.yml

**Comment by oxr463** [comment]
```sh
git clone https://github.com/oxr463/gentoo.git
git clone https://gitlab.com/oxr463/overlay.git
docker run -v "$(pwd):/mnt" -v /var/run/docker.sock:/var/run/docker.sock docker ebuildtester --portage-dir /mnt/gentoo --atom dev-libs/fyaml
```

Bug: https://github.com/nicolasbock/ebuildtester/issues/123
